name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Ensure using the correct Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3 # Update to the latest version
        with:
          name: github-pages
          path: ./path-to-build-artifact # Specify the correct path to the build artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages # Add this environment configuration
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
          token: ${{ secrets.GITHUB_TOKEN }}
